disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Sonic Business Ltd"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

["params.author"]
name = "Sonic Business"
headline = "Punk and counterculture happenings after Sideway based in Canberra, ACT."
bio = "Add bio in config languages"
